name: "Rust: Check Format"
description: Verify that the code is formatted correctly
inputs:
  toolchain:
    description: >-
      Comma-separated list of Rust toolchain specifications. Last version becomes the
      default. -- see https://rust-lang.github.io/rustup/concepts/toolchains.html#toolchain-specification
    required: false
    default: nightly
  cache-shared-key:
    description: >-
      A cache key that is shared across multiple actions. This is used to cache
      dependencies and build outputs.
    required: false
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Rust (${{ inputs.toolchain }})
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: ${{ inputs.toolchain }}
        components: rustfmt
        cache-shared-key: ${{ inputs.cache-shared-key }}

    - name: Run Rustfmt
      shell: bash
      run: cargo fmt --all --check

    - name: Fetch cargo dependencies
      shell: bash
      run: cargo fetch --verbose --locked
